name: Trigger Target Workflow

on:
  push:
    branches:
      - main  # Triggers the action on pushes to the main branch

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_SECERT }}
          repository: kalaikris/githubci-cd  # Replace with the target repo's details
          event-type: trigger-workflow
